/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/setMaterial            Vacuum
/gate/world/geometry/setXLength    301 cm
/gate/world/geometry/setYLength    301 cm
/gate/world/geometry/setZLength    301 cm
/gate/world/vis/setVisible         0

# Slabs
/gate/world/daughters/name   Slab
/gate/world/daughters/insert box
/gate/Slab/geometry/setXLength       10 cm
/gate/Slab/geometry/setYLength       10 cm
/gate/Slab/geometry/setZLength       1 cm
/control/add PLACEMENT1 -{PLACEMENT} 149.5
/gate/Slab/placement/setTranslation  2.5 0 {PLACEMENT1} cm
/gate/Slab/setMaterial               H2C 

/gate/world/daughters/name   Slab2
/gate/world/daughters/insert box
/gate/Slab2/geometry/setXLength       10 cm
/gate/Slab2/geometry/setYLength       10 cm
/gate/Slab2/geometry/setZLength       1 cm
/control/add PLACEMENT2 -{PLACEMENT} 148.5
/gate/Slab2/placement/setTranslation  -2.5 0 {PLACEMENT2} cm
/gate/Slab2/setMaterial               H2C 

# Detection plane
/gate/world/daughters/name                   DetectorPlane
/gate/world/daughters/insert                 box
/gate/DetectorPlane/geometry/setXLength      397.312 mm
/gate/DetectorPlane/geometry/setYLength      297.984 mm
/gate/DetectorPlane/geometry/setZLength      1 nm
/gate/DetectorPlane/placement/setTranslation 0 0 150 cm
/gate/DetectorPlane/setMaterial              Vacuum
/gate/DetectorPlane/vis/setVisible           1
/gate/DetectorPlane/vis/setColor             yellow

# Fluence of gamma
/gate/actor/addActor FluenceActor           DetectorActor
/gate/actor/DetectorActor/save              output/fluence.mhd
/gate/actor/DetectorActor/attachTo          DetectorPlane
/gate/actor/DetectorActor/stepHitType       pre
/gate/actor/DetectorActor/setResolution     2048 1536 1
/gate/actor/DetectorActor/enableUncertainty false

# Physics list
/gate/physics/addPhysicsList emstandard_opt4
/gate/physics/Gamma/SetCutInRegion      world 1 keV
/gate/physics/Electron/SetCutInRegion   world 250 eV
/gate/physics/Positron/SetCutInRegion   world 250 eV
/gate/physics/SetMaxStepSizeInRegion    world 10 um
/gate/physics/ActivateStepLimiter       electron

# Save particles stats
/gate/actor/addActor  SimulationStatisticActor stat
/gate/actor/stat/save output/stats.txt

/gate/run/initialize

# Beam
/control/add SDDOFF {SDD} .1
/control/divide MAG .1 {SDD}
/control/multiply HALFX 397.312 {MAG}
/control/divide HALFX {HALFX} 2
/control/multiply HALFY 297.984 {MAG}
/control/divide HALFY {HALFY} 6
/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle       gamma
/gate/source/mybeam/gps/ene/type       User
/gate/source/mybeam/gps/hist/type      energy
/gate/source/mybeam/gps/pos/halfx      {HALFX} mm
/gate/source/mybeam/gps/pos/halfy      {HALFY} mm
/gate/source/mybeam/gps/pos/rot1       1 0 0
/gate/source/mybeam/gps/pos/rot2       0 1 0
/control/subtract SDDOFF 150 {SDDOFF}
/gate/source/mybeam/gps/pos/centre     0 0 {SDDOFF} cm
/gate/source/mybeam/gps/pos/type       Plane
/gate/source/mybeam/gps/pos/shape      Rectangle
/gate/source/mybeam/gps/ang/type       focused
/control/subtract SDD 150 {SDD}
/gate/source/mybeam/gps/ang/focuspoint 0 0 {SDD} cm
/control/execute mac/100kV.mac

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTotalNumberOfPrimaries {N0}
/gate/application/start

